<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Playbook.Application\Playbook.Application.csproj" />
    <ProjectReference Include="..\Playbook.Infrastructure\Playbook.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Local secrets: dotnet user-secrets set "PropLines:OddsApi:ApiKey" "<key>" -->
    <UserSecretsId>playbook-web-ndoddridge</UserSecretsId>
  </PropertyGroup>

</Project>
